### ISSUE TITLE
idObjectだけだど情報不足？

### ISSUE THREAD

**Issue by TANAKA-Makoto** [onclouds-lab/raas-front-OAS#41]
なんのIDなのかわからないと、使いみちがない？
一応keyで推測はできるけど...
![image](https://user-images.githubusercontent.com/45248369/142250994-0e96506e-c176-438f-92b8-1f39fe3f4cd4.png)

解決案

1. `{type:string,ids:idObject[]}`にする
2. Idを含むendpointで返す
3. uuidなんだから、とりあえず投げれば返るようにする

２だと登録時と引き出すときでまた形がややこしくなる？
３だとDBの検索が大変だし、戻ってくる型が結局わからない

**Comment by TANAKA-Makoto** [comment]
大丈夫っぽい

**Comment by tanihiroki** [comment]
descriptionに書いてあるので、特に問題ないと思います。
今後、mapModel や robotModel を入れて返すことを検討しているなら、（これ、無限ループになりますけど）
array<idObject>  の形でも良いと思いましたが、どっちでも。
