### ISSUE TITLE
spec type のenum化

### ISSUE THREAD

**Issue by TANAKA-Makoto** [onclouds-lab/raas-front-OAS#52]
https://github.com/onclouds-lab/raas-front-OAS/blob/2b4d590d43d555195be587b85187890d97806fbd/models/specs/ElevatorSpecification.json#L10

ここでenum指定されていないので、生成されるTS型が単純なstringになっている。
commonSpecificationと食い違っているのが若干面倒。

しかし各Specでenumにすると記述が増える。(追加があると全部書き加えないといけない)

**Comment by tanihiroki** [comment]
`CommonSpecification`で、`type:string`として、`enum`を書いていますが、それを`allOf`でつなげて、
上わがいた時に、`enum`部分が付いてこないというですね。

各Specで`enum`を記述にしたところで、自動生成される型は、それぞれの`enum`が作成されるんじゃないかな？
（今は、Commonのenumが定義されると思うけど、共通で使われないのではないかと思う。）

もしそうなら、各Spec（例えば、ElevatorSpecification)で `type:string`に入るのは、`elevator` だけなので、
`enum:["elevator"]` だけを書けばよいと思います。ElevatorSpecification に `type:"navigation"`が入る事は無いでしょ？
実際、`type`が増えても書き直すのは、その`type`が入る可能性がある 各Spec だけになるはずです。
（おそらく、Commonだけ）

それでも、`pattern`の記述は多分消せないと思う。なぜなら、`TypeDiscriminator` として作用しているから。
`TypeDiscriminator`とは、文字列から型を特定する識別子です。

**Comment by TANAKA-Makoto** [comment]
> もしそうなら、各Spec（例えば、ElevatorSpecification)で type:stringに入るのは、elevator だけなので、
enum:["elevator"] だけを書けばよいと思います。ElevatorSpecification に type:"navigation"が入る事は無いでしょ？
実際、typeが増えても書き直すのは、そのtypeが入る可能性がある 各Spec だけになるはずです。
（おそらく、Commonだけ）

たしかにこのようにするのが正解な気がします

> それでも、patternの記述は多分消せないと思う。なぜなら、TypeDiscriminator として作用しているから。
TypeDiscriminatorとは、文字列から型を特定する識別子です。

そうですね。これもこのままpatternを残せばいいと思います

**Comment by TANAKA-Makoto** [comment]
↑の変更をプルリクにします。
それで良さそうなら、このissueは閉じます。
