### ISSUE TITLE
attribute として使える文字列は管理しない

### ISSUE THREAD

**Issue by TANAKA-Makoto** [onclouds-lab/raas-front-OAS#54]
robotが取り扱えるattributeは仕様書外の伝達事項として共有する

**Comment by tanihiroki** [comment]
https://github.com/onclouds-lab/raas-front-OAS/blob/232aa0fa5670ccc0b658cd377d70050cc63da2fe/models/common/floorAttribute.json#L12 この部分は説明が変わったので修正が必要かもですね。

**Comment by maShimizu** [comment]
今回は自由文字列とするが, 次期バージョンではリスト/DB管理とする.
Attribute Entity:
name, description, robotsepc(relation)
を持つ.

**Comment by tanihiroki** [comment]
https://github.com/onclouds-lab/raas-front-OAS/pull/55
